version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: puppet
    versions:
    - 7.3.0
    - 7.4.0
    - 7.4.1
  - dependency-name: puppetlabs_spec_helper
    versions:
    - 2.16.0
